# What do want?
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-logging-test
spec:
  name: elasticsearch-logging-test
  storageClassName: managed-premium
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# How do we want it implemented
#apiVersion: storage.k8s.io/v1
#kind: StorageClass
#metadata:
  #name: managed-premium
#provisioner: kubernetes.io/azure-file
#parameters:
 # storageAccount: mongodbstorageakkur
  
