# create your drupal and postgres config here, based off the last assignment
version: '3.1'

services:

  drupal:
    image: custom-drupal
    build: .
    ports:
      - 8080:80
    volumes:
      - drupal-modules:/var/html/modules
      - drupal-profiles:/var/html/profiles
      - drupal-sites:/var/html/sites
      - drupal-themes:/var/html/themes
    restart: always

  postgres:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - drupal-db-data:/var/lib/postgresql/data

    restart: always

volumes:
  drupal-db-data:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
      